/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  headingStyle?: string;
  hr?: string;
  bulletListMarker?: string;
  codeBlockStyle?: string;
  fence?: string;
  emDelimiter?: string;
  strongDelimiter?: string;
  linkStyle?: string;
  linkReferenceStyle?: string;
}
export declare class TurndownService {
  constructor(options?: Options | undefined | null);
  /** Convert HTML to Markdown */
  turndown(html: string): string;
  /** Add a custom rule (currently no-op, rules system simplified) */
  addRule(key: string, filter: string): this;
  /** Keep elements matching the filter as HTML */
  keep(filter: Array<string>): this;
  /** Remove elements matching the filter */
  remove(filter: Array<string>): this;
  /** Escape markdown special characters */
  escape(text: string): string;
}
