/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Options {
  headingStyle?: string;
  hr?: string;
  bulletListMarker?: string;
  codeBlockStyle?: string;
  fence?: string;
  emDelimiter?: string;
  strongDelimiter?: string;
  linkStyle?: string;
  linkReferenceStyle?: string;
}
export declare class TurndownService {
  constructor(options?: Options | undefined | null);
  /** Convert HTML to Markdown using streaming parser */
  turndown(html: string): string;
  /** Add a custom rule (currently no-op) */
  addRule(key: string, filter: string): this;
  /** Keep elements matching the filter as HTML (currently no-op) */
  keep(filter: Array<string>): this;
  /** Remove elements matching the filter (currently no-op) */
  remove(filter: Array<string>): this;
  /** Escape markdown special characters */
  escape(text: string): string;
}
